import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {storyblokInit, apiPlugin} from "@storyblok/react";
import StoryblokProvider from "@/components/StoryBlockProvider";
import {ReactNode} from "react";

const inter = Inter({ subsets: ["latin"] });

storyblokInit({
  accessToken: "CdvK8jUPy8HIuNAgQ8PLvgtt",
  use: [apiPlugin],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:{children:ReactNode}) {
  return (
      <StoryblokProvider>
        <html lang="en">
        <body>{children}</body>
        </html>
      </StoryblokProvider>
  )
}
